name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['12', '10']
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup Deno 0.40
        uses: denolib/setup-deno@220d9c6
        with:
          deno-version: '0.40'
      - run: yarn install --frozen-lockfile
      - run: yarn --check-files
      - run: deno run --allow-read --allow-write https://denopkg.com/wyze/conditional_bisect@v1.0.0/mod.ts
      - run: yarn test:coverage
      - run: yarn bisect-ppx-report send-to Codecov
